In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
import statsmodels.api as sm
from sklearn.naive_bayes import GaussianNB
import scipy.stats as stats
from sklearn import tree
from sklearn.neighbors import KNeighborsClassifier
import xgboost as xgb

In [13]:
data = pd.read_csv('./ailerons.csv')
selected_columns = ['ClimbRate', 'Sgz', 'P', 'Q', 'CurPitch', 'CurRoll', 'AbsRoll', 'DiffClb', 
                    'DiffRollRate', 'DiffDiffClb', 'DiffSeTime1', 'DiffSeTime3', 'DiffSeTime5', 
                    'DiffSeTime7', 'DiffSeTime9', 'DiffSeTime11', 'DiffSeTime13', 'Alpha', 'Se', 'Goal']
selected_features = ['ClimbRate', 'Sgz', 'P', 'Q', 'CurPitch', 'CurRoll', 'AbsRoll', 'DiffClb', 
                    'DiffRollRate', 'DiffDiffClb', 'DiffSeTime1', 'DiffSeTime3', 'DiffSeTime5', 
                    'DiffSeTime7', 'DiffSeTime9', 'DiffSeTime11', 'DiffSeTime13', 'Alpha', 'Se']
# Filter the DataFrame based on selected columns
data = data[selected_columns]

In [14]:
bins = [-np.inf, -0.0025, -0.0020, -0.0015, -0.0010, -0.0005, np.inf]
labels = [0, 1, 2, 3, 4, 5]

# Discretize the 'Goal' column
data['Goal'] = pd.cut(data['Goal'], bins=bins, labels=labels, right=False)
data

ClimbRate  Sgz     P     Q  CurPitch  CurRoll  AbsRoll  DiffClb  \
0            -17   -6 -0.03  0.14      0.59     -0.5      -11       -9   
1           -791   15 -0.28 -0.34      1.11      0.9      -10       27   
2            -46   48 -0.42  0.07      0.57      0.6       -5       -8   
3            496   -5 -0.21 -0.04      0.03     -0.5       -7        6   
4           -124   16 -0.02  0.05      0.61     -0.2       -9       -3   
...          ...  ...   ...   ...       ...      ...      ...      ...   
13745        -53  -13 -0.07  0.02      0.58     -2.3      -15       12   
13746          1    4 -0.11 -0.07      0.47      0.8       -5        8   
13747        425  -14  0.40  0.07      0.41     -2.1      -16       12   
13748        102  -10 -0.19  0.08      1.30      0.5      -10       -3   
13749       -165   52  0.08  0.42      1.07     -1.6      -22      -15   

       DiffRollRate  DiffDiffClb  DiffSeTime1  DiffSeTime3  DiffSeTime5  \
0             0.015         -0.2        0.000       -0.002          0.0   
1            -0.002          4.7        0.000        0.000          0.0   
2            -0.008          0.0       -0.002        0.000          0.0   
3            -0.002         -0.1       -0.001        0.000          0.0   
4             0.000          0.0        0.000        0.000          0.0   
...             ...          ...          ...          ...          ...   
13745         0.022         -0.8        0.000        0.000          0.0   
13746        -0.003         -0.2        0.000        0.000          0.0   
13747         0.031         -0.7        0.000        0.000          0.0   
13748        -0.003         -0.2        0.000        0.000          0.0   
13749         0.007          0.0       -0.002        0.000          0.0   

       DiffSeTime7  DiffSeTime9  DiffSeTime11  DiffSeTime13  Alpha     Se Goal  
0           -0.002        0.000         0.000         0.000    0.6  0.021    4  
1            0.000        0.000         0.000         0.000    0.4  0.013    4  
2            0.000        0.000         0.000         0.000    0.5  0.019    5  
3            0.000        0.000         0.001         0.001    0.5  0.017    5  
4            0.000        0.000         0.000         0.000    0.5  0.018    4  
...            ...          ...           ...           ...    ...    ...  ...  
13745        0.000        0.000         0.000        -0.001    0.5  0.019    4  
13746        0.000        0.000         0.000         0.000    0.5  0.016    5  
13747        0.000        0.001         0.000         0.001    0.9  0.032    3  
13748        0.000        0.000         0.000         0.000    1.4  0.051    3  
13749        0.000        0.000         0.000         0.000    0.9  0.034    2  

[13750 rows x 20 columns]

In [15]:
X = data[selected_features]
y = data['Goal']
X = sm.add_constant(X)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
# Adicionar uma constante para o intercepto

# Criar e treinar o modelo
model = sm.MNLogit(y_train, X_train)
result = model.fit()

# Obter coeficientes
coefficients = result.params

# Calcular odds-ratios
odds_ratios ={
    'Coeficiente': coefficients,
    'Odds-Ratio': np.exp(coefficients)
}


print("Coeficientes e Odds-Ratios:")
print(odds_ratios)

Optimization terminated successfully.
         Current function value: nan
         Iterations 16
Coeficientes e Odds-Ratios:
{'Coeficiente':                0   1   2   3   4
const        NaN NaN NaN NaN NaN
ClimbRate    NaN NaN NaN NaN NaN
Sgz          NaN NaN NaN NaN NaN
P            NaN NaN NaN NaN NaN
Q            NaN NaN NaN NaN NaN
CurPitch     NaN NaN NaN NaN NaN
CurRoll      NaN NaN NaN NaN NaN
AbsRoll      NaN NaN NaN NaN NaN
DiffClb      NaN NaN NaN NaN NaN
DiffRollRate NaN NaN NaN NaN NaN
DiffDiffClb  NaN NaN NaN NaN NaN
DiffSeTime1  NaN NaN NaN NaN NaN
DiffSeTime3  NaN NaN NaN NaN NaN
DiffSeTime5  NaN NaN NaN NaN NaN
DiffSeTime7  NaN NaN NaN NaN NaN
DiffSeTime9  NaN NaN NaN NaN NaN
DiffSeTime11 NaN NaN NaN NaN NaN
DiffSeTime13 NaN NaN NaN NaN NaN
Alpha        NaN NaN NaN NaN NaN
Se           NaN NaN NaN NaN NaN, 'Odds-Ratio':                0   1   2   3   4
const        NaN NaN NaN NaN NaN
ClimbRate    NaN NaN NaN NaN NaN
Sgz          NaN NaN NaN NaN NaN
P            NaN N

/home/araju/anaconda3/envs/IA_TP2/lib/python3.12/site-packages/statsmodels/discrete/discrete_model.py:3027: RuntimeWarning: overflow encountered in exp
  eXB = np.column_stack((np.ones(len(X)), np.exp(X)))
/home/araju/anaconda3/envs/IA_TP2/lib/python3.12/site-packages/numpy/_core/_methods.py:52: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims, initial, where)
/home/araju/anaconda3/envs/IA_TP2/lib/python3.12/site-packages/statsmodels/discrete/discrete_model.py:3028: RuntimeWarning: invalid value encountered in divide
  return eXB/eXB.sum(1)[:,None]


# Naive Bayes

In [16]:
X = data[selected_features]
y = data['Goal']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = GaussianNB()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

# Combinar X_train e y_train para análise
train_data = pd.concat([X_train, y_train], axis=1)

# Separar os dados por classe
classes = train_data['Goal'].unique()
class_data = {cls: data[data['Goal'] == cls][selected_features] for cls in classes}



In [ ]:
def plot_histogram_and_qq(data, attribute, cls):
    plt.figure(figsize=(18, 6))

    # Histograma com KDE
    plt.subplot(1, 2, 1)
    sns.histplot(data[attribute], kde=True)
    plt.title(f'Histograma de {attribute} para a classe {cls}')

    # Gráfico Q-Q
    plt.subplot(1, 2, 2)
    stats.probplot(data[attribute], dist="norm", plot=plt)
    plt.title(f'Gráfico Q-Q de {attribute} para a classe {cls}')

    plt.show()



# Exemplo para um atributo em uma classe
for cls in classes:
    print(f"Classe {cls}")
    for attribute in selected_features:
        print(f"Atributo {attribute}")
        plot_histogram_and_qq(class_data[cls], attribute, cls)


In [26]:
def shapiro_test(data, attribute):
    stat, p = stats.shapiro(data[attribute])
    if p > 0.05:
        return True
    else:
        return False

def test_ks(data, attribute):
    stat, p = stats.kstest(data[attribute], 'norm')
    if p > 0.05:
        return True
    else:
        return False


# Exemplo para um atributo em uma classe
sum = 0
total = 0
for cls in classes:
    for attribute in selected_features:
        sum += shapiro_test(class_data[cls], attribute)
        total += 1
print(f"Quantidade de casos nos quais as variáveis aparentemente seguem uma distribuição normal (Shapiro test): {sum}/{total}")
sum = 0
for cls in classes:
    for attribute in selected_features:
        sum += test_ks(class_data[cls], attribute)
print(f"Quantidade de casos nos quais as variáveis aparentemente seguem uma distribuição normal (Kolmogorov-Smirnov test): {sum}/{total}")

Quantidade de casos nos quais as variáveis aparentemente seguem uma distribuição normal (Shapiro test): 16/114
Quantidade de casos nos quais as variáveis aparentemente seguem uma distribuição normal (Kolmogorov-Smirnov test): 2/114


# Árvores de Decisão

In [59]:
X = data[selected_features]
y = data['Goal']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


MAX_DEPTH = 50
best_f1_test = -1
best_f1_train = -1
best_depth_test = 1
best_depth_train = 1
for i in range(1, MAX_DEPTH+1):

    model = tree.DecisionTreeClassifier(max_depth=i)
    model.fit(X_train, y_train)

    y_pred_train = model.predict(X_train)
    y_pred_test = model.predict(X_test)
    if f1_score(y_train, y_pred_train, average='macro') > best_f1_train:
        best_f1_train = f1_score(y_train, y_pred_train, average='macro')
        best_depth_train = i
    if f1_score(y_test, y_pred_test, average='macro') > best_f1_test:
        best_f1_test = f1_score(y_test, y_pred_test, average='macro')
        best_depth_test = i

print(f"Melhor profundidade para o conjunto de treino: {best_depth_train} (F1-Score: {best_f1_train})")
print(f"Melhor profundidade para o conjunto de teste: {best_depth_test} (F1-Score: {best_f1_test})")



Melhor profundidade para o conjunto de treino: 31 (F1-Score: 1.0)
Melhor profundidade para o conjunto de teste: 7 (F1-Score: 0.5408479290512412)


In [60]:
best_acc_test = -1
best_acc_train = -1
best_depth_test = 1
best_depth_train = 1
for i in range(1, MAX_DEPTH +1):
    model = tree.DecisionTreeClassifier(max_depth=i)
    model.fit(X_train, y_train)

    y_pred_train = model.predict(X_train)
    y_pred_test = model.predict(X_test)
    if accuracy_score(y_train, y_pred_train) > best_acc_train:
        best_acc_train = accuracy_score(y_train, y_pred_train)
        best_depth_train = i
    if accuracy_score(y_test, y_pred_test) > best_acc_test:
        best_acc_test = accuracy_score(y_test, y_pred_test)
        best_depth_test = i

print(f"Melhor profundidade para o conjunto de treino: {best_depth_train} (Acurácia: {best_acc_train})")
print(f"Melhor profundidade para o conjunto de teste: {best_depth_test} (Acurácia: {best_acc_test})")

Melhor profundidade para o conjunto de treino: 31 (Acurácia: 1.0)
Melhor profundidade para o conjunto de teste: 9 (Acurácia: 0.7123636363636363)


In [64]:
best_precision_test = -1
best_precision_train = -1
best_depth_test = 1
best_depth_train = 1
for i in range(1, MAX_DEPTH +1):
    model = tree.DecisionTreeClassifier(max_depth=i)
    model.fit(X_train, y_train)

    y_pred_train = model.predict(X_train)
    y_pred_test = model.predict(X_test)
    if precision_score(y_train, y_pred_train, average='macro', zero_division=0) > best_precision_train:
        best_precision_train = precision_score(y_train, y_pred_train, average='macro', zero_division=0)
        best_depth_train = i
    if precision_score(y_test, y_pred_test, average='macro', zero_division=0) > best_precision_test:
        best_precision_test = precision_score(y_test, y_pred_test, average='macro', zero_division=0)
        best_depth_test = i

print(f"Melhor profundidade para o conjunto de treino: {best_depth_train} (Precisão: {best_precision_train})")
print(f"Melhor profundidade para o conjunto de teste: {best_depth_test} (Precisão: {best_precision_test})")

Melhor profundidade para o conjunto de treino: 31 (Precisão: 1.0)
Melhor profundidade para o conjunto de teste: 12 (Precisão: 0.6081423041296634)


In [57]:
model = tree.DecisionTreeClassifier(max_depth=31)
model.fit(X_train, y_train)

y_pred_train = model.predict(X_train)
y_pred_test = model.predict(X_test)
print("Classification Report (Treino):")
print(classification_report(y_train, y_pred_train))
cm_train = confusion_matrix(y_train, y_pred_train)
print(cm_train)
print("Classification Report (Test):")
print(classification_report(y_test, y_pred_test))
cm_test = confusion_matrix(y_test, y_pred_test)
print(cm_test)

Classification Report (Treino):
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        28
           1       1.00      1.00      1.00       140
           2       1.00      1.00      1.00       586
           3       1.00      1.00      1.00      2124
           4       1.00      1.00      1.00      5705
           5       1.00      1.00      1.00      2417

    accuracy                           1.00     11000
   macro avg       1.00      1.00      1.00     11000
weighted avg       1.00      1.00      1.00     11000

[[  28    0    0    0    0    0]
 [   0  140    0    0    0    0]
 [   0    0  586    0    0    0]
 [   0    0    0 2124    0    0]
 [   0    0    0    0 5705    0]
 [   0    0    0    0    0 2417]]
Classification Report (Test):
              precision    recall  f1-score   support

           0       0.30      0.27      0.29        11
           1       0.34      0.28      0.31        43
           2       0.35      0.39

# KNN

In [79]:
X = data[selected_features]
y = data['Goal']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = KNeighborsClassifier(n_neighbors=3)
model.fit(X_train, y_train)

y_pred_train = model.predict(X_train)
y_pred_test = model.predict(X_test)

print("Classification Report (Test):")
print(classification_report(y_test, y_pred_test))
print(confusion_matrix(y_test, y_pred_test))
print("Classification Report (Treino):")
print(classification_report(y_train, y_pred_train))
print(confusion_matrix(y_train, y_pred_train))

Classification Report (Test):
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        11
           1       0.07      0.09      0.08        43
           2       0.14      0.18      0.16       148
           3       0.29      0.29      0.29       548
           4       0.52      0.58      0.55      1405
           5       0.37      0.25      0.30       595

    accuracy                           0.42      2750
   macro avg       0.23      0.23      0.23      2750
weighted avg       0.41      0.42      0.41      2750

[[  0   0   3   4   4   0]
 [  1   4   6  16  15   1]
 [  0   3  26  47  67   5]
 [  4  24  59 161 281  19]
 [  2  22  71 272 810 228]
 [  0   2  15  61 369 148]]
Classification Report (Treino):
              precision    recall  f1-score   support

           0       0.50      0.61      0.55        28
           1       0.38      0.56      0.45       140
           2       0.50      0.63      0.56       586
           3   

In [80]:

MAX_N_NEIGHBOURS = 10
best_f1_test = -1
best_f1_train = -1
best_n_test = -1
best_n_train = -1
for i in range(1, MAX_N_NEIGHBOURS+1):
    print(i)
    model = KNeighborsClassifier(n_neighbors=i)
    model.fit(X_train, y_train)

    y_pred_train = model.predict(X_train)
    y_pred_test = model.predict(X_test)
    if f1_score(y_train, y_pred_train, average='macro') > best_f1_train:
        best_f1_train = f1_score(y_train, y_pred_train, average='macro')
        best_n_train = i
    if f1_score(y_test, y_pred_test, average='macro') > best_f1_test:
        best_f1_test = f1_score(y_test, y_pred_test, average='macro')
        best_n_test = i
print(f"Melhor profundidade para o conjunto de treino: {best_n_train} (F1-Score: {best_f1_train})")
print(f"Melhor profundidade para o conjunto de teste: {best_n_test} (F1-Score: {best_f1_test})")

1
2
3
4
5
6
7
8
9
10
Melhor profundidade para o conjunto de treino: 1 (F1-Score: 1.0)
Melhor profundidade para o conjunto de teste: 1 (F1-Score: 0.2686303692013086)


# XGBoost

In [49]:
df_results = pd.DataFrame(columns=['n_estimators', 'max_depth', 'learning_rate', 'accuracy', 'precision', 'recall', 'f1'])

In [50]:
X = data[selected_features]
y = data['Goal']
    
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
params = [[50, 4, 0.2],
          [50, 10, 1],
          [50, 10, 0.2],
          [50, 10, 0.04],
          [200, 4, 1],
          [200, 4, 0.2],
          [200, 4, 0.04],
          [200, 10, 0.2]]
for param in params:
    model = xgb.XGBClassifier(n_estimators=param[0], max_depth=param[1], learning_rate=param[2])
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    df_results.loc[len(df_results)] = {
        'n_estimators': param[0],
        'max_depth': param[1],
        'learning_rate': param[2],
        'accuracy': accuracy_score(y_test, y_pred),
        'precision': precision_score(y_test, y_pred, average='macro'),
        'recall': recall_score(y_test, y_pred, average='macro'),
        'f1': f1_score(y_test, y_pred, average='macro')
    } 


In [51]:
df_results

n_estimators  max_depth  learning_rate  accuracy  precision    recall  \
0            50          4           0.20  0.741818   0.644375  0.532611   
1            50         10           1.00  0.730909   0.640172  0.563999   
2            50         10           0.20  0.745091   0.721605  0.602261   
3            50         10           0.04  0.733818   0.636255  0.518340   
4           200          4           1.00  0.722182   0.661521  0.565114   
5           200          4           0.20  0.747273   0.683817  0.589688   
6           200          4           0.04  0.732000   0.591155  0.501509   
7           200         10           0.20  0.748364   0.711768  0.594548   

         f1  
0  0.570893  
1  0.592956  
2  0.646335  
3  0.554529  
4  0.596425  
5  0.621197  
6  0.533165  
7  0.634331